# Generated by Django 5.2.1 on 2025-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Customer mobile number', max_length=20, null=True),
        ),
    ]
