# Generated by Django 5.2.1 on 2025-06-14 06:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('order', '0002_rename_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
        migrations.AddField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=models.CharField(default='Unknown', help_text='Location coordinates or landmark', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='order.order'),
        ),
    ]
