# Generated by Django 5.2.1 on 2025-05-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_remove_cake_type_cake_baker_cake_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'ordering': ['-created_at']},
        ),
    ]
