# Generated by Django 5.2.1 on 2025-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_alter_cake_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
